# Generated by Django 5.2.7 on 2025-10-31 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='disciplina_pessoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='avaliacoes.disciplinapessoa'),
        ),
        migrations.AlterField(
            model_name='avaliacaocategoria',
            name='avaliacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_avaliacao', to='avaliacoes.avaliacao'),
        ),
        migrations.AlterField(
            model_name='disciplinapessoa',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas_pessoa', to=settings.AUTH_USER_MODEL),
        ),
    ]
