# Generated by Django 5.2.7 on 2025-10-29 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0002_avaliacao_updated_at_alter_avaliacao_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='professores_fotos/'),
        ),
    ]
