# Generated by Django 5.2.8 on 2025-11-14 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0002_avaliacao_comentario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='nome_normalized',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='avaliacaocategoria',
            name='nota',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
