# Generated by Django 5.2.7 on 2025-10-29 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0003_professor_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='materia',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
