# Generated by Django 5.2.7 on 2025-10-29 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0004_professor_materia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='materia',
            field=models.CharField(choices=[('BD', 'Banco de Dados'), ('LP', 'Logica de Programação'), ('AE', 'Algoritmos e Estruturas de Dados'), ('SO', 'Sistemas Operacionais'), ('DS', 'Desenvolvimento de Software')], default='MAT', max_length=3),
        ),
    ]
