# Generated by Django 5.2.8 on 2025-12-02 22:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0004_mensagemcontato'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatriculaAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inclusao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Matrícula')),
                ('aluno', models.ForeignKey(limit_choices_to={'user_type': 'aluno'}, on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to=settings.AUTH_USER_MODEL)),
                ('disciplina_professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas_alunos', to='avaliacoes.disciplinapessoa', verbose_name='Disciplina e Professor')),
            ],
            options={
                'verbose_name': 'Matrícula do Aluno',
                'verbose_name_plural': 'Matrículas dos Alunos',
                'unique_together': {('aluno', 'disciplina_professor')},
            },
        ),
    ]
