# Generated by Django 5.2.8 on 2025-12-02 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0005_matriculaaluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriculaaluno',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='avaliacoes.aluno', verbose_name='Aluno Matriculado'),
        ),
    ]
