# Generated by Django 5.2.8 on 2025-12-03 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0006_alter_matriculaaluno_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='aluno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_feitas', to='avaliacoes.aluno'),
        ),
        migrations.AlterUniqueTogether(
            name='avaliacao',
            unique_together={('disciplina_pessoa', 'aluno')},
        ),
    ]
